statistics:
  cost: 20.4181
  makespan: 11.9181
  flowtime: 17.9181
  runtime: 0.0261964
schedule:
  agent0:
    - x: 2
      y: 8
      yaw: 1.57
      t: 0
    - x: 2.0008
      y: 7
      yaw: 1.57
      t: 1
    - x: 2.24639
      y: 6.04134
      yaw: 1.07
      t: 2
    - x: 2.24639
      y: 6.04134
      yaw: 1.07
      t: 3
    - x: 2.24639
      y: 6.04134
      yaw: 1.07
      t: 4
    - x: 2.92153
      y: 5.31779
      yaw: 0.57
      t: 5
    - x: 3.86091
      y: 5.00649
      yaw: 0.0700001
      t: 6
    - x: 4.85846
      y: 4.93655
      yaw: 0.0700001
      t: 7
    - x: 5.85601
      y: 4.86661
      yaw: 0.0700001
      t: 8
    - x: 6.79539
      y: 4.5553
      yaw: 0.57
      t: 9
    - x: 7.47053
      y: 3.83175
      yaw: 1.07
      t: 10
    - x: 7.61812
      y: 3.48991
      yaw: 1.25644
      t: 11
    - x: 7.90199
      y: 2.61681
      yaw: 1.25644
      t: 12
    - x: 8
      y: 2
      yaw: 1.57
      t: 13
  agent1:
    - x: 5
      y: 8
      yaw: 1.57
      t: 0
    - x: 5.0008
      y: 7
      yaw: 1.57
      t: 1
    - x: 5.00159
      y: 6
      yaw: 1.57
      t: 2
    - x: 5.00239
      y: 5
      yaw: 1.57
      t: 3
    - x: 5.00319
      y: 4
      yaw: 1.57
      t: 4
    - x: 5.00318
      y: 3.99521
      yaw: 1.57239
      t: 5
    - x: 5.00158
      y: 2.99521
      yaw: 1.57239
      t: 6
    - x: 5
      y: 2.00479
      yaw: 1.57239
      t: 7
    - x: 5
      y: 2
      yaw: 1.57
      t: 8
