statistics:
  cost: 39.7013
  makespan: 13.7743
  flowtime: 33.7013
  runtime: 0.0768894
schedule:
  agent0:
    - x: 2
      y: 8
      yaw: 1.57
      t: 0
    - x: 2.0008
      y: 7
      yaw: 1.57
      t: 1
    - x: 2.00159
      y: 6
      yaw: 1.57
      t: 2
    - x: 2.00239
      y: 5
      yaw: 1.57
      t: 3
    - x: 2.00319
      y: 4
      yaw: 1.57
      t: 4
    - x: 2.24878
      y: 3.04135
      yaw: 1.07
      t: 5
    - x: 2.92392
      y: 2.31779
      yaw: 0.57
      t: 6
    - x: 3.76582
      y: 1.77816
      yaw: 0.57
      t: 7
    - x: 4.60772
      y: 1.23853
      yaw: 0.57
      t: 8
    - x: 5.5471
      y: 0.927228
      yaw: 0.0700001
      t: 9
    - x: 6.41687
      y: 1.06027
      yaw: 5.90962
      t: 10
    - x: 7.39894
      y: 1.18224
      yaw: 0.126431
      t: 11
    - x: 8.31926
      y: 0.818457
      yaw: 0.626431
      t: 12
    - x: 8.57337
      y: 0.599899
      yaw: 0.794213
      t: 13
    - x: 8.07601
      y: 1.45545
      yaw: 1.29421
      t: 14
    - x: 8
      y: 2
      yaw: 1.57
      t: 15
  agent1:
    - x: 5
      y: 8
      yaw: 1.57
      t: 0
    - x: 5
      y: 8
      yaw: 1.57
      t: 1
    - x: 5
      y: 8
      yaw: 1.57
      t: 2
    - x: 5
      y: 8
      yaw: 1.57
      t: 3
    - x: 5
      y: 8
      yaw: 1.57
      t: 4
    - x: 5
      y: 8
      yaw: 1.57
      t: 5
    - x: 5.0008
      y: 7
      yaw: 1.57
      t: 6
    - x: 5.00159
      y: 6
      yaw: 1.57
      t: 7
    - x: 5.00239
      y: 5
      yaw: 1.57
      t: 8
    - x: 5.00319
      y: 4
      yaw: 1.57
      t: 9
    - x: 5.00318
      y: 3.99521
      yaw: 1.57239
      t: 10
    - x: 5.00158
      y: 2.99521
      yaw: 1.57239
      t: 11
    - x: 5
      y: 2.00479
      yaw: 1.57239
      t: 12
    - x: 5
      y: 2
      yaw: 1.57
      t: 13
  agent2:
    - x: 8
      y: 8
      yaw: 1.57
      t: 0
    - x: 7.75593
      y: 7.04095
      yaw: 2.07
      t: 1
    - x: 7.08195
      y: 6.31633
      yaw: 2.57
      t: 2
    - x: 6.2409
      y: 5.77535
      yaw: 2.57
      t: 3
    - x: 5.39986
      y: 5.23438
      yaw: 2.57
      t: 4
    - x: 4.55882
      y: 4.69341
      yaw: 2.57
      t: 5
    - x: 3.71778
      y: 4.15244
      yaw: 2.57
      t: 6
    - x: 3.63933
      y: 4.10449
      yaw: 2.61598
      t: 7
    - x: 2.99651
      y: 3.73162
      yaw: 2.61598
      t: 8
    - x: 2.28993
      y: 3.03874
      yaw: 2.11598
      t: 9
    - x: 2.00204
      y: 2.09192
      yaw: 1.61598
      t: 10
    - x: 2
      y: 2
      yaw: 1.57
      t: 11
